task:
  name: freebsd
  freebsd_instance:
    # image: freebsd-12-1-release-i386
    image: freebsd-12-1-release-amd64
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain nightly -y
    - . $HOME/.cargo/env
    - rustup toolchain install nightly-i686-unknown-freebsd
    - rustup default nightly-i686-unknown-freebsd
  test_script:
    - . $HOME/.cargo/env
    - cargo build --all --target i686-unknown-freebsd
